name: toolofna-kinect-calibration
channels:
  - default
  - nvidia/label/cuda-11.8.0
  - conda-forge

dependencies:
  - python==3.10
  - cuda-toolkit=11.8.0
  - cudnn
  - ffmpeg
  - pip
  - pip:
      - -r requirements_cuda118.txt